apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-app
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meme-app
  template:
    metadata:
      labels:
        app: meme-app
    spec:
      containers:
        - name: meme-app
          image: wededo4644/weather-app:1670ae0fa7953b644a167ed1a04777fa4582db69
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
