apiVersion: v1
kind: Service
metadata:
  name: weather-app
  namespace: test
spec:
  #type: LoadBalancer
  type: NodePort
  selector:
    app: weather-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 31001
